version: "3.9"

services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - auth-mongo

  upload-service:
    build: ./services/upload-service
    container_name: upload-service
    ports:
      - "5002:5000"
    env_file:
      - .env
    depends_on:
      - upload-mongo

  auth-mongo:
    image: mongo:7
    container_name: auth-mongo
    volumes:
      - auth_db:/data/db

  upload-mongo:
    image: mongo:7
    container_name: upload-mongo
    volumes:
      - upload_db:/data/db

volumes:
  auth_db:
  upload_db:
